// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAleEKdFdrZMQlA53H_UDs8busW_G3sNoA',
    appId: '1:184700476747:web:de4d69e8156236605edcce',
    messagingSenderId: '184700476747',
    projectId: 'lady-zainab-helping-hands',
    authDomain: 'lady-zainab-helping-hands.firebaseapp.com',
    databaseURL: 'https://lady-zainab-helping-hands-default-rtdb.firebaseio.com',
    storageBucket: 'lady-zainab-helping-hands.appspot.com',
    measurementId: 'G-CZCG6M407M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPBi8F2dQBCPMUX55ANUpeILg6EYCeRE',
    appId: '1:184700476747:android:51dcb327780d4e835edcce',
    messagingSenderId: '184700476747',
    projectId: 'lady-zainab-helping-hands',
    databaseURL: 'https://lady-zainab-helping-hands-default-rtdb.firebaseio.com',
    storageBucket: 'lady-zainab-helping-hands.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqkOgl3fs41jLf26_Y1ivKyWaL1x-qskc',
    appId: '1:184700476747:ios:6e79c7a0ca0a97a95edcce',
    messagingSenderId: '184700476747',
    projectId: 'lady-zainab-helping-hands',
    databaseURL: 'https://lady-zainab-helping-hands-default-rtdb.firebaseio.com',
    storageBucket: 'lady-zainab-helping-hands.appspot.com',
    iosBundleId: 'com.example.lzhh',
  );
}
